version: '3'
services:
  mysql:
    image: mysql:8.0
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --skip-ssl --lower_case_table_names=1 --explicit_defaults_for_timestamp --sql_mode=IGNORE_SPACE --max_connections=10000 --wait_timeout=60000 --max_allowed_packet=200M
    environment:
      MYSQL_ROOT_PASSWORD: 1111
      MYSQL_DATABASE: api
    ports:
      - "3310:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
